---
- name: Add InfluxDB repo file
  template: src=influxdb_ubuntu.list.j2 dest=/etc/apt/sources.list.d/influxdb.list owner=root group=root mode=0644
  register: influxdb_list

- name: Add InfluxDB repo key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present
  register: influxdb_key

- name: Update apt cache
  apt: update_cache=yes
  when: influxdb_list.changed == True or influxdb_key.changed == True

- name: Install python-influxdb
  pip: name="{{ item }}" state=latest
  with_items:
   - influxdb

- name: Install InfluxDB
  apt: pkg="{{ item }}" state=latest
  register: influx_installed
  with_items:
   - influxdb

- name: Fix permissions on InfluxDB data folder
  become: true
  file: path="/var/lib/influxdb" state=directory owner=influxdb group=influxdb recurse=true

- name: Set configuration for InfluxDB
  become: true
  ini_file:
    dest: /etc/influxdb/influxdb.conf
    section: http
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'enabled',             value: "true" }
    - { option: 'bind-address',        value: "127.0.0.1:8086" }

- name: Restart InfluxDB
  become: true
  service: name=influxdb enabled=yes state=started
  register: influx_started
  ignore_errors: true

- name: Pause to allow InfluxDB to spin up
  wait_for: port=8086 delay=5
  when: influx_started.changed

- name: Create 'stations' database
  influxdb_database:
    hostname: "localhost"
    database_name: "{{ item }}"
    state: present
  with_items:
    - 'stations'

- name: Create 'stations' retention policies
  influxdb_retention_policy:
    hostname: "localhost"
    database_name: "stations"
    policy_name: "{{ item.name }}"
    duration: "{{ item.duration }}"
    default: "{{ item.default }}"
    replication: 1
  with_items:
   - { name: '15s', duration: '5d', default: true }
   - { name: '1h', duration: '2w', default: false }
   - { name: '1d', duration: 'INF', default: false }

- name: Manage continuous queries on 'stations'
  influxdb_downsample:
    database: "stations"
    retentions: "1h:1h,1d:1d"
    measurements: [{'measurement':':MEASUREMENT', 'fields': ['min(value) AS min','mean(value) AS value','max(value) AS max']}]
    prune: true

- name: Lock down InfluxDB to localhost requests
  replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: 'bind-address = ":80'
    replace: 'bind-address = "localhost:80'
    backup: yes
  when: app_env == "production"