---
  - name: Install InfluxDB
    become: true
    apt: deb=https://dl.influxdata.com/influxdb/releases/influxdb_1.0.0_amd64.deb
    register: influx_installed

  - name: restart influxdb
    service: name=influxdb enabled=yes state=restarted
    when: influx_installed.changed

  - name: Set up Initial InfluxDB Database
    when: influx_installed.changed
    shell: "curl -i -XPOST http://localhost:8086/query --data-urlencode 'q={{ item }}'"
    args:
      warn: no
    with_lines: "cat {{ util_base }}/influx_create.txt"

  - name: Update InfluxDB
    when: influx_installed.changed == false
    shell: "curl -i -XPOST http://localhost:8086/query --data-urlencode 'q={{ item }}'"
    args:
      warn: no
    with_lines: "cat {{ util_base }}/influx_update.txt"

  - name: Lock down InfluxDB query and admin ports
    ini_file:
      dest: /etc/influxdb/influxdb.conf
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "admin", option: "bind-address", value: "localhost:8083" }
      - { section: "http", option: "bind-address", value: "localhost:8086" }
    when: app_env == "production"
    notify: restart-influxdb