---
  - name: Install InfluxDB 0.8.8
    become: true
    apt: deb=http://influxdb.s3.amazonaws.com/influxdb_0.8.8_amd64.deb

  - name: restart influxdb
    service: name=influxdb enabled=yes state=restarted

  - pause: seconds=15 prompt="Wait for InfluxDB to initialize"

  - name: Set up Initial InfluxDB Database
    uri:
      url: http://localhost:8086/cluster/database_configs/stations?u=root&p=root
      method: POST
      body: "{{ lookup('file', util_base+'/influx_stations.json') }}"
      body_format: json
      status_code: 201
    ignore_errors: true