---
- name: Add InfluxDB repo file
  template: src=influxdb_ubuntu.list.j2 dest=/etc/apt/sources.list.d/influxdb.list owner=root group=root mode=0644
  register: influxdb_list

- name: Add InfluxDB repo key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present
  register: influxdb_key

- name: Update apt cache
  apt: update_cache=yes
  when: influxdb_list.changed == True or influxdb_key.changed == True

- name: Install python-influxdb
  pip: name="{{ item }}" state=latest
  with_items:
   - influxdb

- name: Install InfluxDB
  apt: pkg="{{ item }}" state=latest
  register: influx_installed
  with_items:
   - influxdb

- name: Disable service initialization for influxdb
  become: true
  service: name=influxdb enabled=no state=stopped
  ignore_errors: true

- name: restart influxdb
  supervisorctl:
    name: 'core:influxdb'
    state: restarted
  when: influx_installed.changed

#- name: Pause to allow InfluxDB to spin up
#  pause: seconds=15
#  when: influx_installed.changed

- name: Create 'stations' database
  influxdb_database:
    hostname: "localhost"
    database_name: "{{ item }}"
    state: present
  with_items:
    - 'stations'

- name: Create 'stations' retention policies
  influxdb_retention_policy:
    hostname: "localhost"
    database_name: "stations"
    policy_name: "{{ item.name }}"
    duration: "{{ item.duration }}"
    default: "{{ item.default }}"
    replication: 1
  with_items:
   - { name: '15s', duration: '5d', default: true }
   - { name: '1h', duration: '2w', default: false }
   - { name: '1d', duration: 'INF', default: false }

- name: Manage continuous queries on 'stations'
  influxdb_downsample:
    database: "stations"
    retentions: "1h:1h,1d:1d"
    measurements: [{'measurement':':MEASUREMENT', 'fields': ['min(value) AS min','mean(value) AS value','max(value) AS max']}]
    prune: true

- name: Lock down InfluxDB to localhost requests
  replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: 'bind-address = ":80'
    replace: 'bind-address = "localhost:80'
    backup: yes
  when: app_env == "production"
  notify: restart influxdb