---
  - name: Install InfluxDB
    become: true
    apt: deb=https://dl.influxdata.com/influxdb/releases/influxdb_1.0.0_amd64.deb
    register: influx_installed

  - name: restart influxdb
    service: name=influxdb enabled=yes state=restarted
    when: influx_installed.changed

  - name: Set up Initial InfluxDB Database
    when: influx_installed.changed
    shell: "curl -i -XPOST http://localhost:8086/query --data-urlencode 'q={{ item }}'"
    args:
      warn: no
    with_lines: "cat {{ util_base }}/influx_create.txt"

  - name: Update InfluxDB
    when: influx_installed.changed == false
    shell: "curl -i -XPOST http://localhost:8086/query --data-urlencode 'q={{ item }}'"
    args:
      warn: no
    with_lines: "cat {{ util_base }}/influx_update.txt"

  - name: Lock down InfluxDB to localhost requests
    replace:
      dest: /etc/influxdb/influxdb.conf
      regexp: 'bind-address = ":80'
      replace: 'bind-address = "localhost:80'
      backup: yes
    when: app_env == "production"
    notify: restart influxdb