---
  - name: Install IceCast2 (14.04)
    become: true
    apt: deb=http://downloadcontent.opensuse.org/repositories/multimedia:/xiph/xUbuntu_14.04/amd64/icecast2_2.4.2-2_amd64.deb
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

  - name: Install IceCast2 (16.04)
    become: true
    apt: pkg=icecast2 state=latest
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

  - name: Link Fallback Error MP3
    file: src="{{ www_base }}/resources/error.mp3" dest="/usr/share/icecast2/web/error.mp3" state=link

  - name: Remove problematic LiquidSoap plugins
    become: true
    apt: pkg="{{ item }}" state=absent
    with_items:
     - liquidsoap-plugin-all
     - liquidsoap-plugin-opus

  - name: Install LiquidSoap
    become: true
    apt: pkg="{{ item }}" install_recommends=yes state=latest
    with_items:
     - liquidsoap
     - liquidsoap-plugin-ogg
     - liquidsoap-plugin-vorbis
     - liquidsoap-plugin-lame
     - liquidsoap-plugin-flac
     - liquidsoap-plugin-icecast

  - name: Download ShoutCast 2 (x86)
    get_url:
      url: http://download.nullsoft.com/shoutcast/tools/sc_serv2_linux-latest.tar.gz
      dest: "{{ app_base }}/servers/sc_serv.tar.gz"
    when: ansible_architecture == 'i386'

  - name: Download ShoutCast 2 (x64)
    get_url:
      url: http://download.nullsoft.com/shoutcast/tools/sc_serv2_linux_x64-latest.tar.gz
      dest: "{{ app_base }}/servers/sc_serv.tar.gz"
    when: ansible_architecture == 'x86_64'

  - name: Extract ShoutCast 2 Binary
    unarchive:
      src: "{{ app_base }}/servers/sc_serv.tar.gz"
      dest: "{{ app_base }}/servers/"
      remote_src: yes
      creates: "{{ app_base }}/servers/sc_serv"
      mode: "u=rwx,g=rx,o=rx"
      owner: "azuracast"
      group: "www-data"
    when: ansible_architecture == 'x86_64' or ansible_architecture == 'i386'

