---
  - include: x86.yml
    dynamic: no
    when: ansible_architecture == 'x86_64' or ansible_architecture == 'i386'

  - include: armhf.yml
    dynamic: no
    when: ansible_architecture != 'x86_64' and ansible_architecture != 'i386'