---
engines:
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
    checks:
      Similar code:
        enabled: false
      Identical code:
        enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: php,phtml
      rulesets: codesize,design,unusedcode
ratings:
  paths:
  - "**.js"
  - "**.php"
  - "**.phtml"
exclude_paths:
  - tests/_support/_generated/
  - web/static/bower_components
  - web/static/js/app.js
  - web/static/js/app.min.js