image: docker

services:
  - gitlab/dind

stages:
 - test

run_testing:
  stage: test
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker-compose up -d
    - docker-compose -f docker-compose.sample.yml -f docker-compose.testing.yml pull
    - docker-compose -f docker-compose.sample.yml -f docker-compose.testing.yml run --rm cli azuracast_install
    - docker-compose -f docker-compose.sample.yml -f docker-compose.testing.yml run --rm cli azuracast_testing
    - cat tests/_output/*.html
  only:
    - master