stages:
 - test
 - on_failure

run_testing:
  image: docker/compose:1.19.0
  stage: test
  script:
    - docker-compose -f docker-compose.sample.yml -f docker-compose.testing.yml pull
    - docker-compose -f docker-compose.sample.yml -f docker-compose.testing.yml run --rm cli azuracast_install
    - docker-compose -f docker-compose.sample.yml -f docker-compose.testing.yml run --rm cli azuracast_testing
  only:
    - master
  tags:
    - docker

echo_testing_logs:
  stage: on_failure
  script:
    - cat tests/_output/*.html
  when: on_failure