language: php

php:
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: true

install:
  - chmod a+x $TRAVIS_BUILD_DIR/install.sh
  - $TRAVIS_BUILD_DIR/install.sh

script:
  - php codecept run
