language: php

php:
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: required
dist: trusty

install:
  - chmod a+x $TRAVIS_BUILD_DIR/install.sh
  - chmod a+rx -R $TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/install.sh

script:
  - cd $TRAVIS_BUILD_DIR && ./vendor/bin/codecept run
