language: php

php:
  - 7.0

git:
  depth: 1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: required
dist: trusty

install:
  - chmod a+x $TRAVIS_BUILD_DIR/testing.sh
  - chmod a+rx -R $TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/testing.sh

before_script:
  - phpenv config-add $TRAVIS_BUILD_DIR/util/travis_php.ini

script:
  - cd $TRAVIS_BUILD_DIR && ./vendor/bin/codecept run --no-interaction --coverage --coverage-xml --fail-fast

after_failure:
  - cat $TRAVIS_BUILD_DIR/tests/_output/*

after_success:
  - cd $TRAVIS_BUILD_DIR && CODECLIMATE_REPO_TOKEN=88a1e1f82e680833f40445f1455b2a4a8f92628db1f0ea4bb9c4a5057b70e889 ./vendor/bin/test-reporter --coverage-report=tests/_output/coverage.xml