git:
  depth: 1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: required
dist: trusty

services:
  - docker

install:
  - docker-compose up -d

script:
 - docker-compose run web azuracast_testing

after_failure:
 - docker-compose run web cat /var/azuracast/www/tests/_output/*