version: '2'

services:
  nginx:
    build:
      context: ./util/docker/nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
      - stations
    volumes:
      - .:/var/azuracast/www

  mariadb:
    build:
      context: ./util/docker/mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azur4c457
      - MYSQL_DATABASE=azuracast

  influxdb:
    image: 'influxdb:alpine'
    volumes:
      - influx_data:/var/lib/influxdb

  web:
    build:
      context: ./util/docker/web
    depends_on:
      - mariadb
      - influxdb
      - stations
    volumes:
      - .:/var/azuracast/www
      - cache_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations

  cron:
    build:
      context: ./util/docker/web
    depends_on:
      - mariadb
      - influxdb
      - stations
    volumes:
      - .:/var/azuracast/www
      - cache_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
    depends_on:
      - mariadb
      - influxdb
      - stations
    command: 'cron && tail -f /var/log/cron.log'

  stations:
    build:
      context: ./util/docker/stations
    ports:
     - '8000-8500:8000-8500'
    volumes:
     - station_data:/var/azuracast/stations

volumes:
  db_data: {}
  influx_data: {}
  station_data: {}
  cache_data: {}