version: '2'

services:
  static:
    build:
      context: ./util/docker/static
    volumes:
      - ./web/static:/src

  stations_cli:
    image: azuracast/azuracast_stations:latest
    volumes:
     - station_data:/var/azuracast/stations
    command: 'bash'

  mariadb:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"

  chronograf:
    image: chronograf:alpine
    ports:
     - "8888:8888"
    command: "chronograf --influxdb-url=http://influxdb:8086"