version: '3'

services:
  nginx:
    build: ./util/docker/nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-tier
    depends_on:
      - web
    volumes:
      - ${pwd}:/var/azuracast/www

  mariadb:
    build: ./util/docker/mariadb
    networks:
      - app-tier
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azur4c457
      - MYSQL_DATABASE=azuracast

  influxdb:
    image: 'influxdb:alpine'
    networks:
      - app-tier
    volumes:
      - influx_data:/var/lib/influxdb

  web:
    build: ./util/docker/web
    networks:
      - app-tier
    depends_on:
     - mariadb
     - influxdb
     - stations
    volumes:
      - ${pwd}:/var/azuracast/www
      - cache_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations

  cron:
    build: ./util/docker/web
    networks:
      - app-tier
    depends_on:
      - web
    volumes:
      - ${pwd}:/var/azuracast/www
      - station_data:/var/azuracast/stations
    command: 'cron && tail -f /var/log/cron.log'

  stations:
    build: ./util/docker/stations
    ports:
     - '8000-8500:8000-8500'
    networks:
     - app-tier
    volumes:
     - station_data:/var/azuracast/stations

networks:
  app-tier:

volumes:
 db_data:
 influx_data:
 station_data:
 cache_data: