version: '2'

services:
  static:
    build:
      context: ./util/docker/static
    volumes:
      - ./web/static:/var/azuracast/www/web/static

  stations:
    ports:
     - '8000-8500:8000-8500'

  stations_cli:
    image: azuracast/azuracast_stations:latest
    volumes:
     - station_data:/var/azuracast/stations
    command: 'bash'

  mariadb:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"