---
  - name: Install nginx
    become: true
    apt:  pkg=nginx state=latest

  - name: Change default nginx site
    become: true
    template: src=default.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx