---
- hosts: all
  become: true
  vars:
    util_base: "{{ playbook_dir | dirname }}"
    www_base: "{{ util_base | dirname }}"
    app_base: "{{ www_base | dirname }}"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "development"
    testing_mode: false

    dev_azuracast_user_password: "azuracast"
    dev_mysql_root_password: "password"

  roles:
    - init
    - git
    - azuracast-user
    - azuracast-config
    - azuracast-radio
    - influxdb
    - supervisord
    - nginx
    - php
    - mariadb
    - composer
    - azuracast-db
    - { role: azuracast-cron, when: testing_mode == false }
    - { role: azuracast-build, when: testing_mode == false and app_env == 'development' }