---
- hosts: all
  become: true
  vars:
    util_base: "{{ playbook_dir | dirname }}"
    www_base: "{{ util_base | dirname }}"
    app_base: "{{ www_base | dirname }}"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "development"

    dev_azuracast_user_password: "azuracast"
    dev_mysql_root_password: "password"

  roles:
    - init
    - { role: python, when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty' }
    - git
    - azuracast-radio
    - azuracast-user
    - azuracast-config
    - influxdb
    - nginx
    - php-phalcon
    - mariadb
    - composer
    - azuracast-db
    - azuracast-cron
    - { role: azuracast-build, when: app_env == 'development' }
    - { role: vim, when: app_env == 'development' }