---
- hosts: all
  become: true
  vars:
    util_base: "{{ playbook_dir | dirname }}"
    www_base: "{{ util_base | dirname }}"
    app_base: "{{ www_base | dirname }}"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    testing_mode: false

  roles:
    - init
    - azuracast-config
    - azuracast-update
    - azuracast-radio
    - php
    - influxdb
    - azuracast-cron