---
- hosts: all
  become: true
  vars:
    util_base: "{{ playbook_dir | dirname }}"
    www_base: "{{ util_base | dirname }}"
    app_base: "{{ www_base | dirname }}"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    testing_mode: false
    update_revision: 1

  roles:
    - init
    - azuracast-config
    - { role: azuracast-radio, when: update_revision|int < 8 }

    - { role: nginx, when: update_revision|int < 10 }
    - { role: php, when: update_revision|int < 10 }
    - { role: supervisord, when: update_revision|int < 11 }
    - { role: influxdb, when: update_revision|int < 10 }
    - { role: ufw, when: update_revision|int < 12 }

    - { role: azuracast-cron, when: update_revision|int < 2 }
    - azuracast-update