---
  - name: Install Node
    become: true
    apt:  pkg="{{ item }}" state=latest
    with_items:
     - nodejs
     - npm

  - name: Symlink Nodejs Binary
    become: true
    file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

  - name: Create build directory
    file: path="{{ app_base }}/build" state=directory owner=azuracast group=www-data mode=0777

  - name: Symlink Nodejs Binary
    become: true
    file: src="{{ www_base }}/web/static/{{ item }}" dest="{{ app_base }}/build/{{ item }}" state=link
    with_items:
     - yarn.lock
     - gruntfile.js
     - package.json

  - name: Install Node global packages
    shell: "npm install -g {{ item }} --loglevel warn"
    with_items:
     - bower
     - grunt
     - yarn

  - name: Install Node packages
    shell: "yarn --loglevel warn"
    args:
      chdir: "{{ app_base }}/build"

  - name: Install Developer Tools
    become: true
    apt:  pkg="{{ item }}" state=latest
    with_items:
     - vim
     - gettext