---
- name: Assign User Password
  set_fact:
    redis_service_name: "{{ 'redis-server' if ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty' else 'redis' }}"

- name: Enable and restart all core services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
   - "influxdb"
   - "mysql"
   - "php7.1-fpm"
   - "nginx"
   - "{{ redis_service_name }}"