---
  - name: Add PHP PPA repository
    become: true
    apt_repository: repo=ppa:ondrej/php

  - name: Add Phalcon PPA repository
    become: true
    shell: curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash
    args:
      warn: no

  - name: Update apt again
    become: true
    apt:  update_cache=yes

  - name: Install PHP Libraries
    become: true
    apt:  package="{{ item }}" state=latest
    with_items:
     - php7.0-fpm
     - php7.0-cli
     - php7.0-gd
     - php7.0-mysqlnd
     - php7.0-curl
     - php7.0-xml
     - php7.0-phalcon

  - name: Configure PHP FPM Pool
    template: src=fpmpool.j2 dest=/etc/php/7.0/fpm/pool.d/www.conf force=true
    notify: restart php-fpm

  - name: Configure php-fpm php.ini
    ini_file:
      dest: /etc/php/7.0/fpm/php.ini
      section: PHP
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { option: 'post_max_size',       value: "50M" }
      - { option: 'short_open_tag',      value: "On" }
      - { option: 'upload_max_filesize', value: "25M" }
    notify: restart php-fpm

  - name: Configure php-cli php.ini
    ini_file:
      dest: /etc/php/7.0/cli/php.ini
      section: PHP
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { option: 'short_open_tag',      value: "On" }