---
  - name: Clear AzuraCast Cache
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php cache:clear
    when: azuracast_db_created.changed and testing_mode|bool == false

  - name: Apply All DB Migrations
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php migrations:migrate --no-interaction --allow-no-migration
    when: azuracast_db_created.changed