---
  - name: Ensure update script continues to be executable
    file: path="{{ item }}" state=touch mode="a+x"
    with_items:
     - "{{ www_base }}/update.sh"
     - "{{ www_base }}/docker-update.sh"

  - name: Update Composer directory permissions
    become: true
    file: path="{{ item }}" state=directory owner=azuracast group=www-data recurse=true
    with_items:
     - "{{ www_base }}/vendor"

  - name: Install Composer Dependencies (Development)
    become: true
    become_user: azuracast
    shell: composer install
    args:
      chdir: "{{ www_base }}"
    when: app_env == "development"

  - name: Install Composer Dependencies (Production)
    become: true
    become_user: azuracast
    shell: composer install --no-dev
    args:
      chdir: "{{ www_base }}"
    when: app_env == "production"

  - name: Update configuration from legacy
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php azuracast:config:migrate

  - name: Clear AzuraCast Cache
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php cache:clear

  - name: Update Database
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php migrations:migrate --no-interaction --allow-no-migration

  - name: Regenerate Doctrine Proxies
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php orm:generate-proxies

  - name: Restart Radio Stations
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php azuracast:radio:restart

