---
  - name: Ensure update script continues to be executable
    file: path="{{ item }}" state=touch mode="a+x"
    with_items:
     - "{{ www_base }}/update.sh"
     - "{{ www_base }}/docker-update.sh"

  - name: Update configuration from legacy
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php azuracast:config:migrate

  - name: Clear AzuraCast Cache
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php cache:clear

  - name: Update Database
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php migrations:migrate --no-interaction --allow-no-migration

  - name: Regenerate Doctrine Proxies
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php orm:generate-proxies

  - name: Restart Radio Stations
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php azuracast:radio:restart

