---
  - name: Reset local git
    shell: git reset --hard
    args:
      chdir: "{{ www_base }}"
      warn: no

  - name: Pull new Git repository
    shell: git pull
    args:
      chdir: "{{ www_base }}"
      warn: no

  - name: Make update script executable again
    file: path="{{ www_base }}/update.sh" state=touch mode="a+x"

  - name: Clear AzuraCast Cache
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php cache:clear

  - name: Update Doctrine Database
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/doctrine.php orm:schema-tool:update --force --complete

