---
  - name: Reset local git
    shell: git reset --hard
    args:
      chdir: "{{ www_base }}"
      warn: no
    when: app_env == "production"

  - name: Pull new Git repository
    shell: git pull
    args:
      chdir: "{{ www_base }}"
      warn: no
    when: app_env == "production"

  - name: Make update script executable again
    file: path="{{ www_base }}/update.sh" state=touch mode="a+x"

  - name: Install Composer Dependencies (Development)
    become: true
    shell: composer install
    args:
      chdir: "{{ www_base }}"
    when: app_env == "development"

  - name: Install Composer Dependencies (Production)
    become: true
    shell: composer install --no-dev
    args:
      chdir: "{{ www_base }}"
    when: app_env == "production"

  - name: Clear AzuraCast Cache
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php cache:clear

  - name: Update Doctrine Database
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php orm:schema-tool:update --force --complete

  - name: Restart Radio Stations
    become: true
    become_user: azuracast
    shell: php {{ util_base }}/cli.php radio:restart

