---
  - name: Update apt
    become: true
    apt:  update_cache=yes

  - name: Install system packages
    become: true
    apt:  pkg="{{ item }}" state=latest
    with_items:
      - apt-transport-https
      - curl
      - wget
      - build-essential
      - python-software-properties
      - pwgen
      - whois