---
  - debug:
      msg: "Running Ansible on {{ inventory_hostname }} with OS {{ ansible_distribution }} {{ ansible_distribution_release }} {{ ansible_distribution_version }} {{ ansible_architecture }} ({{ app_env }})"

  - debug:
      msg: "Running in Testing Mode."
    when: testing_mode|bool == true

  - name: Add multiverse repository
    apt_repository: repo="{{item}}"
    when: ansible_distribution == 'Ubuntu'
    with_items:
      - "deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse"
      - "deb-src http://archive.ubuntu.com/ubuntu/  {{ansible_distribution_release}} multiverse"
      - "deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse"
      - "deb-src http://archive.ubuntu.com/ubuntu/  {{ansible_distribution_release}}-updates multiverse"

  - name: Update apt
    become: true
    apt:  update_cache=yes

  - name: Install system packages
    become: true
    apt:  pkg="{{ item }}" state=latest
    with_items:
      - apt-transport-https
      - curl
      - wget
      - tar
      - build-essential
      - python-software-properties
      - pwgen
      - whois
      - python-pip
      - lnav

  - name: Update pip components
    pip: name="{{ item }}" state=latest
    with_items:
     - pip

  - name: Check if systemd is running
    stat: path=/run/systemd/system
    register: systemd