---
 - name: (Prod) Generate MySQL User Password
   command: pwgen 8 -sn 1
   register: prod_mysql_user_password
   when: app_env == "production"

 - name: Assign User Password
   set_fact:
     mysql_user_password: "{{ prod_mysql_user_password.stdout if app_env == 'production' else dev_mysql_user_password }}"

 - name: Add repo file
   template: src=mariadb_ubuntu.list.j2 dest=/etc/apt/sources.list.d/mariadb.list owner=root group=root mode=0644
   register: mariadb_list
   when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

 - name: Add repo key
   apt_key: id=1BB943DB url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCBCB082A1BB943DB state=present
   register: mariadb_key
   when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

 - name: Update apt cache
   apt: update_cache=yes
   when: mariadb_list.changed == True or mariadb_key.changed == True

 - name: Unattended package installation
   shell: export DEBIAN_FRONTEND=noninteractive
   changed_when: false

 - name: Install MariaDB
   apt: pkg="{{ item }}" state=present
   with_items:
     - mariadb-server
     - mariadb-client

 - name: Add configuration
   template: src=my.cnf.j2 dest=/etc/mysql/conf.d/my.cnf owner=root group=root mode=0644
   notify: restart mysql

 - name: Start and enable service
   service: name=mysql state=started enabled=yes

 - name: Add empty root .my.cnf (if none exists)
   become: true
   template: src=root_empty_my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

# - name: MySQL Root Account Fix (Ubuntu 16.04)
#   become: true
#   shell: "cat {{ util_base }}/xenial_mysql_fix.sql | mysql --defaults-extra-file=/root/.my.cnf -NB"
#   when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

 - name: Remove anonymous users
   command: 'mysql --defaults-extra-file=/root/.my.cnf -ne "{{ item }}"'
   with_items:
     - "DELETE FROM mysql.user WHERE User=''"
   changed_when: False

 - name: Disallow root login remotely
   command: 'mysql --defaults-extra-file=/root/.my.cnf -ne "{{ item }}"'
   with_items:
     - "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
   changed_when: False

 - name: Remove test database and access to it
   command: 'mysql --defaults-extra-file=/root/.my.cnf -ne "{{ item }}"'
   with_items:
     - "DROP DATABASE test"
     - "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
   changed_when: False
   ignore_errors: True

 # MySQL Secure Installation
 - name: Set up AzuraCast database user
   mysql_user:
     name: azuracast
     host: "localhost"
     password: "{{ mysql_user_password }}"
     priv: "azuracast.*:ALL,GRANT"
     state: present
   notify: send mysql notification

 #- name: Reload privilege tables
 #  command: 'mysql -ne "{{ item }}"'
 #  with_items:
 #    - "FLUSH PRIVILEGES"
 #  changed_when: False

 - name: Add .my.cnf
   become: true
   template: src=user_my.cnf.j2 dest="{{ app_base }}/.my.cnf" owner=azuracast group=azuracast mode=0600 force=yes

 - name: Reload privilege tables
   command: 'mysql --defaults-extra-file=/root/.my.cnf -ne "{{ item }}"'
   with_items:
     - "FLUSH PRIVILEGES"
   changed_when: False

 # Create Database
 - name: Create MySQL Database
   mysql_db:
     config_file: "/root/.my.cnf"
     name: azuracast
     state: present
     collation: utf8mb4_unicode_ci
     encoding: utf8mb4
   register: azuracast_db_created

 - name: Write DB configuration
   become: true
   template: src=db.conf.php.j2 dest="{{ www_base }}/app/config/db.conf.php" owner=azuracast group=www-data mode=0644 force=yes